version: '3.8'

services:

  api:
    build: ./
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgresql://postgres:admin@db:5432/auth_users
    depends_on:
      - db

  db:
    image: postgres:13.4
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_users
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=en_US.UTF-8
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./db_vol:/var/lib/postgresql/data
